name = "nezha-panel-simple"
main = "worker.js"
compatibility_date = "2024-01-01"

# 环境变量配置示例（实际部署时在Cloudflare Dashboard中配置）
[vars]
# 这些变量需要在Cloudflare Workers Dashboard中配置
# ACCOUNTS_JSON = '[{"host":"your-server.com","port":22,"username":"user","password":"pass","cron":"cd ~/nezhapanel && pm2 start ./dashboard"}]'
# TELEGRAM_BOT_TOKEN = "your_bot_token"
# TELEGRAM_CHAT_ID = "your_chat_id"
# SSH_PROXY_URL = "https://your-ssh-proxy.herokuapp.com"

# Workers配置
[build]
command = ""

# 路由配置（可选）
# [[routes]]
# pattern = "nezha.yourdomain.com/*"
# zone_name = "yourdomain.com"